# fly.toml app configuration file generated for soli on 2023-07-19T14:19:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soli"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
