databases:
  - name: soli
    databaseName: soli
    user: soli

services:
  - type: web
    name: soli
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soli
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
